<footer>
    <img src="images/logo.jpg" alt="Swinburne Software Group - logo">
    <table>
        <tr>
            <th>Contact us:</th>
            <td><a class="footerLink" href="mailto:104544926@student.swin.edu.au">104544926@student.swin.edu.au</a></td>
            <th>Find us:</th>
            <td><a class="footerLink" href="https://www.google.com/maps/place/Swinburne+University+of+Technology/@-37.8217283,145.0352537,15.52z/data=!4m15!1m8!3m7!1s0x6ad642326bae5aaf:0x75e96bbd4988f769!2sSwinburne+University+of+Technology!8m2!3d-37.8221504!4d145.0389546!10e1!16zL20vMDFrcV9z!3m5!1s0x6ad642326bae5aaf:0x75e96bbd4988f769!8m2!3d-37.8221504!4d145.0389546!16zL20vMDFrcV9z">Swinburne Hawthorn campus</a></td>
            <th>Find out about us:</th>
            <td><a class="footerLink" href="about.html">about.html</a></td>
        </tr>
        <tr>
            <td></td>
            <td><a class="footerLink" href="tel:0490757830">+61 490 757 830</a></td>
            <td></td>
            <td></td>
        </tr>
    </table>
<footer>